name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Configure AWS credentials
      run: |
        export TF_VAR_aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}
        export TF_VAR_aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        export TF_VAR_aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
